Use conf.d directory instead of changing my.cnf
juju-solutions/charm-mysql pull request #11
Opened 2017-03-08 13:40 UTC by fnordahl

Remove default values from template, use default values
maintained by distribution instead.

Include only values we want to override in the charm
provided config file.

Tested by hand on Ubuntu precise, trusty and xenial.

Fixes #9

2017-03-20 16:55 UTC, marcoceppi requested changes
This is a great enhancement to the charm, one nitpick on permission notation

2017-03-20 16:55 UTC, marcoceppi commented on hooks/config-changed
> +        os.chmod(t.name, 0644)
Could we have this be `0o644`

2017-03-21 08:31 UTC, fnordahl commented on hooks/config-changed
> +        os.chmod(t.name, 0644)
Thx, and done. New push on the way.

2017-03-21 08:33 UTC, fnordahl commented
New amended commit pushed that should address the permission notation issue.

2017-03-21 14:36 UTC, merged

2017-03-21 17:39 UTC, marcoceppi commented
Available in [cs:mysql-57](https://jujucharms.com/mysql/57)